# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
rvm:
 - 3.5.0
sudo: false
before_install:
  - tlmgr install index
warnings_are_errors: true
cache: packages
repos:
  CRAN: https://cloud.r-project.org



