# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
rvm:
 - 3.5.0
sudo: false
warnings_are_errors: true
cache: packages
env:
  global:
    - RENV="./pkg-build.sh"    # r-builder
    - R_BUILD_ARGS="--no-manual"
    - R_CHECK_ARGS="--no-manual --as-cran"
  matrix:
    - RVERSION=devel _R_VALGRIND_=TRUE _R_CHECK_FULL_=TRUE


